server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/springbootbase?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBeh
    username: root
    password: "123456"
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
      password:
cache:
  default-exp: 3600
# MyBatis Plus??
mybatis-plus:
  # ??mapper?????????mapper.xml????
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      updateStrategy: not_null
      insertStrategy: not_null
      logic-delete-field: is_deleted # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl