server:
  port: 8080

spring:
  profiles:
    active: "@activeProfile@"
cache:
  default-exp: 3600
# MyBatis Plus??
mybatis-plus:
  # ??mapper?????????mapper.xml????
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      updateStrategy: not_null
      insertStrategy: not_null
      logic-delete-field: is_deleted # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#minio
minio:
  endpoint: http://minio:9000
  bucket-name: springbootbase
  access-key: lychee
  secret-key: wzyhlj999455

#qiniu
qiniu:
    access-key: cDTIxDl80ob6spBqsBUO1OH3mfPYH1kunV0lWxSl
    secret-key: JdSp2PiEKVAprapHeDlrFc7HNUXa5DN3Rm3nkXaK
    bucket-name: lycheevip
    domain: http://rr039i7tv.bkt.clouddn.com
    expireSeconds: 7200

jwt:
  secret: sdhuishiuwqeiuwfoes
  expiration: 1800
  header: Authorization
  prefix: "Bearer "