version: "2.15.7"

services:
  spring_boot_base:
    image: springbootbase:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    container_name: SpringBootBase
    environment:
      TZ: "Asia/Shanghai"
    external_links:
      - minio:minio
      - mysql:mysql5
      - redis:redis6
    networks:
      - app_net
networks:
    app_net:
        external: true